/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-03 12:12:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.InputStream;
import java.io.IOException;
import java.util.Properties;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1677844534000L));
    _jspx_dependants.put("jar:file:/mnt/servers/apache-tomcat-9.0.73/webapps/gameoflife/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153385082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.io.InputStream");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>The Game Of Life</title>\n");
      out.write("    <!--  TODO: Don't inline this -->\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("        h2 {\n");
      out.write("            color: blue;\n");
      out.write("            font-family: sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .intro {\n");
      out.write("            font-family: sans-serif;\n");
      out.write("            background: rgb(200, 200, 200);\n");
      out.write("            border: 1pt rgb(150, 150, 150) solid;\n");
      out.write("            padding: 8px;\n");
      out.write("            margin: 4px;\n");
      out.write("            text-align: justify;\n");
      out.write("            color: rgb(25, 25, 25)\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .footer {\n");
      out.write("            color: white;\n");
      out.write("            font-size: medium;\n");
      out.write("            text-align: right;\n");
      out.write("            background-color: blue;\n");
      out.write("            margin-top: 100px;\n");
      out.write("            border-top: thin solid black;\n");
      out.write("            padding: 2px;\n");
      out.write("            font-family: sans-serif;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-button {\n");
      out.write("            border-bottom: 2px solid rgb(100, 100, 100);\n");
      out.write("            border-left: 2px solid rgb(100, 100, 100);\n");
      out.write("            border-top: 2px solid rgb(150, 150, 150);\n");
      out.write("            border-right: 2px solid rgb(150, 150, 150);\n");
      out.write("            background: silver;\n");
      out.write("            width: 100px;\n");
      out.write("            margin: 8px;\n");
      out.write("            padding: 4px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: large;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-family: sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        li {\n");
      out.write("            list-style: circle;\n");
      out.write("            padding: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h2>Welcome to Conway's Game Of Life!</h2>\n");
      out.write("\n");
      out.write("<div class=\"intro\">\n");
      out.write("    <p>This is a really cool web version of Conway's famous Game Of\n");
      out.write("        Life. The Game of Life is a cellular automaton devised by the British\n");
      out.write("        mathematician John Horton Conway way back in 1970.</p>\n");
      out.write("\n");
      out.write("    <p>The universe of the Game of Life is an infinite two-dimensional\n");
      out.write("        orthogonal grid of square cells, each of which is in one of two possible\n");
      out.write("        states, live or dead. Every cell interacts with its eight neighbors,\n");
      out.write("        which are the cells that are directly horizontally, vertically, or\n");
      out.write("        diagonally adjacent. At each step in time, the following transitions\n");
      out.write("        occur:\n");
      out.write("    <ul>\n");
      out.write("        <li>Any live cell with fewer than two live neighbours dies, as if\n");
      out.write("            caused by underpopulation.\n");
      out.write("        </li>\n");
      out.write("        <li>Any live cell with more than three live neighbours dies, as if\n");
      out.write("            by overcrowding.\n");
      out.write("        </li>\n");
      out.write("        <li>Any live cell with two or three live neighbours lives on to\n");
      out.write("            the next generation.\n");
      out.write("        </li>\n");
      out.write("        <li>Any dead cell with exactly three live neighbours becomes a\n");
      out.write("            live cell.\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("    </p>\n");
      out.write("</div>\n");
      out.write("\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<div class=\"action-button\">\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${newGamePage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">New Game</a>\n");
      out.write("</div>\n");
      out.write("\n");

    InputStream inputStream = this.getClass().getClassLoader().getResourceAsStream("/system.properties");
    Properties prop = new Properties();
    String appVersion = "";
    if (inputStream != null) {
        try {
            prop.load(inputStream);
            appVersion = prop.getProperty("app.version");
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }

      out.write("\n");
      out.write("<div class=\"footer\">Game Of Life version ");
      out.print(appVersion);
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/home.jsp(94,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/game/new");
      // /WEB-INF/jsp/home.jsp(94,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("newGamePage");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
